version: "3.4"

services:
  litellm:
    image: "${REPOSITORY_URL}/base/litellm-database:main-stable"
    container_name: deps-litellm
    command:
      - "--config=/app/config/config.yaml"
    ports:
      - "4000:4000"
    volumes:
      - ./etc/litellm/config.yaml:/app/config/config.yaml
    env_file:
      - ./etc/litellm/.env
      - ./.env
    networks:
      - deps-network
    restart: unless-stopped

networks:
  deps-network:
    external: true
